# In Class Notebook, Week 02

You can access this notebook in near-real time by going here: https://github.com/UIUC-iSchool-DataViz/is445_obuobg_spring2026/blob/main/week02/inClass_week02.ipynb

For plain rendering, past URL into the nbviewer interface (note, sometimes takes a refresh):

https://kokes.github.io/nbviewer.js/viewer.html

What I just did was `ESC+m` to turn this into a markdown cell (this might be different on other interfaces like VSCode).

I will now press `SHIFT+RETURN` to "render" this cell.

In [1]:
1+2

3

# Make a large header

## Make slightly smaller header

### Even smaller

#### Smallest

This is regular text.

Ordered list:
1. thing 1
1. thing 2
1. thing 3

Unordered list:
* bullet point 1
* bullet point 2
* bullet point 3

This also supports LaTeX: $\frac{x}{y}=5$

$$\frac{z}{a} = 6$$

In [2]:
import pandas as pd # importing pandas as pd so that I can use "pd" as a shorthand

In [4]:
#pd.read_csv?

In [5]:
buildings = pd.read_csv('https://github.com/UIUC-iSchool-DataViz/is445_data/raw/main/building_inventory.csv')

In [7]:
buildings.head(n=2)

,Agency Name,Location Name,Address,City,Zip code,County,Congress Dist,Congressional Full Name,Rep Dist,Rep Full Name,...,Bldg Status,Year Acquired,Year Constructed,Square Footage,Total Floors,Floors Above Grade,Floors Below Grade,Usage Description,Usage Description 2,Usage Description 3
0,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,1975,1975,144,1,1,0,Unusual,Unusual,Not provided
1,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided

In [8]:
# subset by row index
buildings.iloc[0:3] # <-- note the "i" in "iloc"

,Agency Name,Location Name,Address,City,Zip code,County,Congress Dist,Congressional Full Name,Rep Dist,Rep Full Name,...,Bldg Status,Year Acquired,Year Constructed,Square Footage,Total Floors,Floors Above Grade,Floors Below Grade,Usage Description,Usage Description 2,Usage Description 3
0,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,1975,1975,144,1,1,0,Unusual,Unusual,Not provided
1,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
2,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided